### ISSUE TITLE
Postgres Support

### ISSUE THREAD

**Issue by slobo** [bbkr/exodus#1]
Sounds like Exodus would be a good tool for database subsetting, say getting part of production data into dev environment. After a quick peek it seems only MySQL is supported - do you think Postgres support would be hard to add?
Thanks for a great article!

**Comment by bbkr** [comment]
Hi

We actually use Exodus all the time to extract part of production data and analyse reported issues in isolated environment.

Yes, PostgreSQL will be supported. I'm in the middle of refactoring it to Perl 6 - with proper abstract interface that will allow pluggable database engines. Estimated release will be in about 2 weeks.

Also it will allow to mark certain columns as anonymised (will be passed through user-provided function). This way developer can work on production data without need of extra clearance for accessing personally identifiable information.

**Comment by bbkr** [comment]
https://github.com/bbkr/UpRooted - Done. New tool with MySQL and PostgreSQL support.
